name: worker-testw
on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: npm install -g gomtm
        shell: bash
      - run: gomtm
